# https://github.com/actions/labeler

# Add label to the PRs changing files under llm_bench/
llm_bench:
- changed-files:
  - any-glob-to-any-file:
    - 'llm_bench/**'
    - '.github/workflows/llm_bench-python.yml'

WWB:
- changed-files:
  - any-glob-to-any-file:
    - 'llm_bench/python/who_what_benchmark/**'
