# https://github.com/actions/labeler
name: label PRs

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    paths:
      - llm_bench/python/**
      - .github/workflows/llm_bench-python.yml

permissions: read-all  # Required by https://github.com/ossf/scorecard/blob/e23b8ad91fd6a64a0a971ca4fc0a4d1650725615/docs/checks.md#token-permissions

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/labeler@v5
      with:
        configuration-path: '.github/label_config.yml'
